# Site settings
title: goSammy
description: > # this means to ignore newlines until "baseurl:"
  I'm an iOS software developer by day with a passion for UI & UX design.
  Also a fake Harry Potter fan, super allergic to cats, and tolerator of soggy
  cereal.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gosammy.com" # the base hostname & protocol for your site
twitter_username: senmu
github_username:  senmu

# Build settings
markdown: kramdown

paginate: 4

author: Sam Lu

gems: [jekyll-paginate]
