# Site settings
title: goSammy
description: > # this means to ignore newlines until "baseurl:"
    I'm Sam. I like design & developing for iOS.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gosammy.com" # the base hostname & protocol for your site
twitter_username: senmu
github_username:  senmu

# Build settings
markdown: kramdown

paginate: 4

author: Sam Lu

gems: [jekyll-paginate]
